### ISSUE TITLE
feature request - optionally mention corepack in the pnpm installation instructions

### ISSUE THREAD

**Issue by rdewaele** [prinsss/just-pnpm#1]
Thank you for creating this package, I found it suggested here: https://github.com/npm/cli/issues/2660#issuecomment-1764148955

### Request

The current output does not mention the corepack alternative mode of installation:
> If you don't have pnpm, install it via "npm i -g pnpm".

Would you be open to providing the option to suggest the corepack installation method instead?
https://nodejs.org/api/corepack.html

### Context

With corepack, running `yarn` immediately results in this error:
> Usage Error: This project is configured to use pnpm

But `npm install` still just works. ( I am not sure whether this is a deliberate corepack design decision. )
This is of course where this package comes in.

However, we now run the risk of developers installing pnpm globally, while they are expected to enable corepack and setup pnpm that way.

**Comment by prinsss** [comment]
Hi,

I understand your concerns. Actually the output message was copied from the original [only-allow](https://github.com/pnpm/only-allow/blob/v1.2.1/bin.js#L39) package, and I wasn't aware of that.

Since there are many more methods to install pnpm (npm, corepack, Homebrew, Scoop, etc.) and different teams may have different conventions on how to configure package managers, maybe it would be better to provide a link to the official installation guide instead?

```text
Use "pnpm install" for installation in this project.

If you don't have pnpm, go to https://pnpm.io/installation
and find installation method that suits your environment.
```

**Comment by rdewaele** [comment]
Thank you for your consideration and I think you make a good point and suggestion.

**Comment by prinsss** [comment]
`just-pnpm@1.0.2` was released with the new message mentioned above. Thank you! ❤️
