### ISSUE TITLE
Meaningless error when workspace packages are used

### ISSUE THREAD

**Issue by cefn** [prinsss/just-pnpm#2]
Before using a workspace package I get a meaningful error that guides users of the repository to use pnpm...

```sh
(main)$ npm install
npm ERR! code 1
pnpm@1.0.2/node_modules/just-pnpm
npm ERR! command failed
npm ERR! command sh -c node ./index.js
npm ERR! Use "pnpm install" for installation in this project.
npm ERR! 
npm ERR! If you don't have pnpm, go to https://pnpm.io/installation
npm ERR! and find installation method that suits your environment.
```

However, once I use a [workspace protocol package](https://pnpm.io/workspaces#workspace-protocol-workspace), there is no meaningful error I just get a npm error which offers no guidance to users how to fix it...

```sh
(main)$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

**Comment by prinsss** [comment]
Hi,

Sorry for the late reply. But I don't think that this is a problem with the `just-pnpm` package.

You are trying to run `npm install` in a project whose `package.json` contains some pnpm-specific stuffs like `workspace:`.
This will lead to an error because `npm` doesn't understand it, and the error message is also quite clear -- Unsupported URL Type "workspace:".

Unfortunately, this error message can not be changed by us, because it is thrown by `npm` itself in a very early stage of the installation process.

P.S. The main purpose of this package is to prevent users from accidentally running `npm install` in a project that uses `pnpm` as package manager. In this case, users are actually unable to run `npm install` due to the error.

**Comment by cefn** [comment]
Yeah it's a good point that this error prevents `just-pnpm` from doing its thing but ALSO prevents `npm` from doing its thing which is of primary importance. 

However, the reason this is a problem, is that `Unsupported URL Type "workspace:".` looks like something you might need to fix and could waste devs time because they got no hint that this was a `pnpm` project and therefore the error is spurious. 

I thought I'd share it as a data point in case there's any other intervention that can be made which prevents `npm` from getting as far as attempting to resolve packages, and which allows some kind of 'please use pnpm' message from being served beforehand. If there's no earlier stage that we can intervene then our hands are tied.

**Comment by prinsss** [comment]
> I thought I'd share it as a data point in case there's any other intervention that can be made which prevents npm from getting as far as attempting to resolve packages, and which allows some kind of 'please use pnpm' message from being served beforehand. If there's no earlier stage that we can intervene then our hands are tied.

I'm afraid that there is no other [lifecycle hook](https://docs.npmjs.com/cli/v10/using-npm/scripts) that we can use to intervene before the dependency resolution stage.

While it's hard to restrict it technically, what we can do now is to add a strong warning message in the documentation of projects which use pnpm workspaces, to inform the users that they should use pnpm instead of npm.
